local function entry(name, loader)
	return { Name = name, Load = loader }
end

local Registry = {
	entry("Fly", function() return require("./Movement/Fly") end),
	entry("CFrameFly", function() return require("./Movement/CFrameFly") end),
	entry("VehicleFly", function() return require("./Movement/VehicleFly") end),
	entry("AirWalk", function() return require("./Movement/AirWalk") end),
	entry("Noclip", function() return require("./Movement/Noclip") end),
	entry("NoFall", function() return require("./Movement/NoFall") end),
	entry("StepMove", function() return require("./Movement/StepMove") end),
	entry("PlayerESP", function() return require("./Visual/PlayerESP") end),
	entry("Highlight", function() return require("./Visual/Highlight") end),
	entry("NameTag", function() return require("./Visual/NameTag") end),
	entry("AntiKick", function() return require("./Utility/AntiKick") end),
	entry("AntiVoid", function() return require("./Utility/AntiVoid") end),
	entry("Teleport", function() return require("./Utility/Teleport") end),
	entry("InstantInteraction", function() return require("./Utility/InstantInteraction") end),
	entry("Zoom", function() return require("./Utility/Zoom") end),
	entry("Freecam", function() return require("./Utility/Freecam") end),
	entry("Aimbot", function() return require("./Combat/Aimbot") end),
	entry("AimbotSimple", function() return require("./Combat/AimbotSimple") end),
	entry("Fling", function() return require("./Combat/Fling") end),
	entry("Spin", function() return require("./Combat/Spin") end),
	entry("Tornado", function() return require("./Combat/Tornado") end),
	entry("Orbit", function() return require("./Combat/Orbit") end),
	entry("Defense", function() return require("./Combat/Defense") end),
	entry("HandleKill", function() return require("./Combat/HandleKill") end),
	entry("TPWalk", function() return require("./Movement/TPWalk") end),
	entry("TPJump", function() return require("./Movement/TPJump") end),
	entry("ScrollSwitch", function() return require("./Movement/ScrollSwitch") end),
	entry("SnapTurn", function() return require("./Movement/SnapTurn") end),
	entry("SnapReverse", function() return require("./Movement/SnapReverse") end),
	entry("ChatSpy", function() return require("./Chat/ChatSpy") end),
	entry("ChatSpammer", function() return require("./Chat/ChatSpammer") end),
	entry("ChatControl", function() return require("./Chat/ChatControl") end),
	entry("ChatTag", function() return require("./Visual/ChatTag") end),
	entry("Footstep", function() return require("./Visual/Footstep") end),
	entry("Landing", function() return require("./Visual/Landing") end),
	entry("LoopOof", function() return require("./Visual/LoopOof") end),
	entry("Movable", function() return require("./Visual/Movable") end),
	entry("NPCHigh", function() return require("./Visual/NPCHigh") end),
	entry("PlayerLight", function() return require("./Visual/PlayerLight") end),
	entry("Invisible", function() return require("./Visual/Invisible") end),
	entry("TriggerESP", function() return require("./Visual/TriggerESP") end),
	entry("AntiLook", function() return require("./Utility/AntiLook") end),
	entry("ClickInspect", function() return require("./Utility/ClickInspect") end),
	entry("ClickDelete", function() return require("./Utility/ClickDelete") end),
	entry("AntiFling", function() return require("./Utility/AntiFling") end),
	entry("GameTP", function() return require("./Utility/GameTP") end),
	entry("GuiDeleter", function() return require("./Utility/GuiDeleter") end),
	entry("LockCam", function() return require("./Utility/LockCam") end),
	entry("MouseUnlock", function() return require("./Utility/MouseUnlock") end),
	entry("PartCleaner", function() return require("./Utility/PartCleaner") end),
	entry("PartTP", function() return require("./Utility/PartTP") end),
	entry("PassBypass", function() return require("./Utility/PassBypass") end),
	entry("Spectator", function() return require("./Utility/Spectator") end),
	entry("ServerFinder", function() return require("./Utility/ServerFinder") end),
	entry("Translator", function() return require("./Utility/Translator") end),
	entry("SysMsg", function() return require("./Utility/SysMsg") end),
	entry("TCPTrigger", function() return require("./Utility/TCPTrigger") end),
	entry("DeathBall", function() return require("./Games/DeathBall") end),
	entry("Doors", function() return require("./Games/Doors") end),
	entry("Drawme", function() return require("./Games/Drawme") end),
	entry("IceCream", function() return require("./Games/IceCream") end),
	entry("Gifts", function() return require("./Games/Gifts") end),
	entry("FullESP", function() return require("./Visual/FullESP") end),
	entry("WorldShader", function() return require("./Visual/WorldShader") end),
	entry("PlayerControl", function() return require("./Utility/PlayerControl") end),
	entry("FlyV4", function() return require("./Movement/FlyV4") end),
	entry("External", function() return require("./Utility/External") end),
}

return Registry
